Added guide on migrations with scheduler
substrate-developer-hub/substrate-how-to-guides pull request #76
Opened 2021-09-06 17:31 UTC by midegdugarova

2021-09-08 07:47 UTC, sacha-l commented
@midegdugarova: thanks this is great. Moving in the direction we want to go with regards to making clear what content is "how-to guide" worthy and what is more of a knowledgebase article. It would be great to do some refactoring of all our current Parachain guides and take out all content that can become a knowledgebase article. That way we can do more explicit pointing to "how to do this thing" and making the separation from "what are the things I could do" - just like the changes I committed here to add that clarity. 

Creating technical knowledgebase material for Parachains stuff is something we need in our Knowledgebase IMO. Looping in @SBalaguer and @shawntabrizi to get your thoughts on direction here.

2021-09-12 10:40 UTC, sacha-l commented
@SBalaguer : I think it's a good start for this type of material - slim isn't a bad thing for how-to guides. Its better to have slim than distracting. 

A better starting point imo for parachain content in general would be to create knowledge base articles. A lot of the guides we have right now are probably best suited as Knowledgebase articles. [This one](https://substrate.dev/substrate-how-to-guides/docs/parachains/b-runtime-upgrades/runtime-upgrades#2-choose-your-upgrade-approach) for example, takes the reader through different approaches rather than how to accomplish something specific and potentially technically challenging. A how-to guide should have a clear, single-track scope stepping through how to accomplish one thing. Let's sync up on this, I would love to see more articles and coordinate efforts to create relevant how-to guides!

2021-09-12 11:48 UTC, sacha-l requested changes
After a second pass here, I've added some additional review notes addressing instances where things could use a little more clarity. Thanks again @midegdugarova for taking this on. Hope my feedback makes sense!

2021-09-12 11:48 UTC, sacha-l commented on docs/07-parachains/b-runtime-upgrades/upgrade-scheduler.md
> +# How to use scheduler pallet for storage migrations
```suggestion
# How to use the scheduler pallet for storage migrations 
```

2021-09-12 11:48 UTC, sacha-l commented on docs/07-parachains/b-runtime-upgrades/upgrade-scheduler.md
> +Ensure the extrinsics can only be called via root.
Add that this happens inside your pallet from which you want to schedule calls. And that this is the extrinsic that schedules the migration code. Nicer to be explicit.

2021-09-12 11:48 UTC, sacha-l commented on docs/07-parachains/b-runtime-upgrades/upgrade-scheduler.md
> +```rust
Nice to have one sentence prefacing the code snippet here. E.g.: Add two types to your pallet's Configuration trait. Also, what's the relevance of `ScheduledCall` ? Looks like there's a reason but its not clear to me at this stage.

2021-09-12 11:48 UTC, sacha-l commented on docs/07-parachains/b-runtime-upgrades/upgrade-scheduler.md
> +- use the [```schedule_named```](https://github.com/paritytech/substrate/blob/master/frame/scheduler/src/lib.rs#L404)  function.
Again, one sentence is nice to give specific context - e.g.: Use the [`schedule_named`](https://github.com/paritytech/substrate/blob/master/frame/scheduler/src/lib.rs#L404) method from the `Scheduler` pallet  to trigger your migration extrinsic. 

Also, single back ticks are sufficient for single terms :)

2021-09-12 11:48 UTC, sacha-l commented on docs/07-parachains/b-runtime-upgrades/upgrade-scheduler.md
> +### 3. Schedule the calls within  the  ```on_runtime_upgrade``` hook
```suggestion
### 3. Schedule the calls within  the  `on_runtime_upgrade` hook  
```

2021-09-12 11:48 UTC, sacha-l commented on docs/07-parachains/b-runtime-upgrades/upgrade-scheduler.md
> +
One last step would be nice here to come full circle. The goal of this guide was to:
"Implement storage migration logic using Substrate’s Scheduler pallet for non-core migrations" which we've met. But Step 4 could just point to either another guide on how to trigger runtime migrations using this technique, or it could describe what to do, with references where relevant.

2021-09-15 10:55 UTC, midegdugarova commented on docs/07-parachains/b-runtime-upgrades/upgrade-scheduler.md
> +
@sacha-l could you check the link on line 83? I think I did it wrong

2021-09-16 18:50 UTC, sacha-l approved these changes

2021-09-16 18:50 UTC, sacha-l commented on docs/07-parachains/b-runtime-upgrades/upgrade-scheduler.md
> +
Works for me ! :)

2021-09-16 18:50 UTC, merged