Update NoteToViewer.js
substrate-developer-hub/substrate-how-to-guides pull request #9
Opened 2021-05-12 19:10 UTC by NukeManDan

more concise stab at the intro 🤞🏼 you like it - open to edits!

2021-05-12 23:16 UTC, sacha-l requested changes

2021-05-12 23:16 UTC, sacha-l commented on how-to-substrate/src/components/NoteToViewer.js
> +            into <em>runtime</em> an <em>node</em> logic that produce robust
```suggestion
            into <em>runtime</em> and <em>node</em> logic to produce robust
```

2021-05-14 19:32 UTC, sacha-l approved these changes

2021-05-17 23:40 UTC, sacha-l commented
Not sure what's causing the conflict here @NukeManDan, do you know?

2021-05-18 02:02 UTC, NukeManDan commented
moving to #11

2021-05-18 02:02 UTC, closed without merging